name: Pull Request

on:
  pull_request:
    paths:
      - 'pyinsights/**'
      - 'tests/**'
      - poetry.lock
      - pyproject.toml

jobs:
  lint:
    name: Lint Check
    strategy:
      matrix:
        python: [3.8]
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run lint check
        run: make lint

  unittest:
    name: Unit Test
    strategy:
      matrix:
        python: [3.8]
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run unit test
        run: make test

  mypy:
    name: Typing hints Check
    strategy:
      matrix:
        python: [3.8]
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run mypy
        run: make mypy