name: Release package to PyPI and GitHub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi:
    name: Release to pypi
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-dev

      - name: Release
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pyinsights_uploader }}
        run: make release

  github:
    name: Release to GitHub
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true